correction dockerfile

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,82 +1,180 @@
 FROM nvcr.io/nvidia/l4t-jetpack:r35.4.1
 
-ENV DEBIAN_FRONTEND=noninteractive \
-    CUDA_HOME=/usr/local/cuda \
-    PATH=${CUDA_HOME}/bin:${PATH} \
-    LD_LIBRARY_PATH=${CUDA_HOME}/lib64:/usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra-egl:${LD_LIBRARY_PATH} \
-    DISPLAY=:0 \
-    OPENCV_VERSION=4.10.0 \
-    CMAKE_VERSION=3.28.1 \
-    OPENBLAS_CORETYPE=ARMV8 \
-    LANG=es_ES.UTF-5 \
-    LANGUAGE=es_ES:es \
-    LC_ALL=es_ES.UTF-5
-|
-# ===== COMPILADORES =====
+# Variables de entorno
+ENV DEBIAN_FRONTEND=noninteractive
+ENV CUDA_HOME=/usr/local/cuda
+ENV PATH=${CUDA_HOME}/bin:${PATH}
+ENV LD_LIBRARY_PATH=${CUDA_HOME}/lib64:/usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra-egl:${LD_LIBRARY_PATH}
+ENV DISPLAY=:0
+ENV OPENCV_VERSION=4.10.0
+ENV CMAKE_VERSION=3.28.1
+ENV OPENBLAS_CORETYPE=ARMV8
+ENV LANG=es_ES.UTF-8
+ENV LANGUAGE=es_ES:es
+ENV LC_ALL=es_ES.UTF-8
+
+# Compiladores
 RUN apt-get update && apt-get install -y \
-    software-properties-common wget curl git \
-    && add-apt-repository ppa:ubuntu-toolchain-r/test \
-    && apt-get update \
-    && apt-get install -y \
-        gcc-11 g++-11 gcc-9 g++-9 \
-        build-essential pkg-config \
-    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 \
-        --slave /usr/bin/g++ g++ /usr/bin/g++-11 \
-        --slave /usr/bin/gcov gcov /usr/bin/gcov-11 \
-    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 \
-        --slave /usr/bin/g++ g++ /usr/bin/g++-9 \
-        --slave /usr/bin/gcov gcov /usr/bin/gcov-9 \
+    software-properties-common \
+    wget \
+    curl \
+    git \
     && rm -rf /var/lib/apt/lists/*
 
-# ===== CMAKE ACTUALIZADO =====
+RUN add-apt-repository ppa:ubuntu-toolchain-r/test && apt-get update
+
+RUN apt-get install -y \
+    gcc-11 \
+    g++-11 \
+    gcc-9 \
+    g++-9 \
+    build-essential \
+    pkg-config \
+    && rm -rf /var/lib/apt/lists/*
+
+RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 \
+    --slave /usr/bin/g++ g++ /usr/bin/g++-11 \
+    --slave /usr/bin/gcov gcov /usr/bin/gcov-11
+
+RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 \
+    --slave /usr/bin/g++ g++ /usr/bin/g++-9 \
+    --slave /usr/bin/gcov gcov /usr/bin/gcov-9
+
+# CMake actualizado
 WORKDIR /tmp
-RUN wget -q https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-aarch64.tar.gz \
-    && tar -xzf cmake-${CMAKE_VERSION}-linux-aarch64.tar.gz -C /opt \
-    && ln -sf /opt/cmake-${CMAKE_VERSION}-linux-aarch64/bin/cmake /usr/local/bin/cmake \
-    && ln -sf /opt/cmake-${CMAKE_VERSION}-linux-aarch64/bin/ctest /usr/local/bin/ctest \
-    && ln -sf /opt/cmake-${CMAKE_VERSION}-linux-aarch64/bin/cpack /usr/local/bin/cpack \
-    && rm -f cmake-${CMAKE_VERSION}-linux-aarch64.tar.gz
+RUN wget -q https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-aarch64.tar.gz
+RUN tar -xzf cmake-${CMAKE_VERSION}-linux-aarch64.tar.gz -C /opt
+RUN ln -sf /opt/cmake-${CMAKE_VERSION}-linux-aarch64/bin/cmake /usr/local/bin/cmake
+RUN ln -sf /opt/cmake-${CMAKE_VERSION}-linux-aarch64/bin/ctest /usr/local/bin/ctest
+RUN ln -sf /opt/cmake-${CMAKE_VERSION}-linux-aarch64/bin/cpack /usr/local/bin/cpack
+RUN rm -f cmake-${CMAKE_VERSION}-linux-aarch64.tar.gz
 
-# ===== DEPENDENCIAS MULTIMEDIA Y DISPLAY =====
+# Dependencias multimedia
 RUN apt-get update && apt-get install -y \
-    libjpeg-dev libpng-dev libtiff-dev libwebp-dev \
-    libopenexr-dev libopenjp2-7-dev \
-    libavcodec-dev libavformat-dev libswscale-dev libavresample-dev \
-    libv4l-dev libxvidcore-dev libx264-dev libx265-dev libvpx-dev \
-    libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
-    libgstreamer-plugins-good1.0-dev libgstreamer-plugins-bad1.0-dev \
-    gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools \
-    gstreamer1.0-plugins-good gstreamer1.0-plugins-bad \
-    libgtk-3-dev libgtk2.0-dev \
-    libatlas-base-dev gfortran \
-    libeigen3-dev libtbb-dev libtbb2 libdc1394-22-dev \
-    libgl1-mesa-dev libglu1-mesa-dev libglew-dev \
-    libxrender-dev libxrandr-dev libxcursor-dev libxinerama-dev libxi-dev \
-    libxext6 libsm6 libice6 x11-apps mesa-utils \
-    ffmpeg v4l-utils net-tools iputils-ping \
+    libjpeg-dev \
+    libpng-dev \
+    libtiff-dev \
+    libwebp-dev \
+    libopenexr-dev \
+    libopenjp2-7-dev \
     && rm -rf /var/lib/apt/lists/*
 
-# ===== LIBRERÍAS C++ =====
 RUN apt-get update && apt-get install -y \
-    libspdlog-dev libgoogle-glog-dev libgflags-dev \
-    libfmt-dev libjsoncpp-dev nlohmann-json3-dev \
-    libyaml-cpp-dev libprotobuf-dev protobuf-compiler \
-    libmsgpack-dev libsqlite3-dev libpq-dev libmysqlclient-dev \
-    libhiredis-dev libzmq3-dev libcurl4-openssl-dev libssl-dev \
-    libwebsocketpp-dev libmicrohttpd-dev \
-    libboost-all-dev libarmadillo-dev \
-    libopenblas-dev liblapack-dev libgsl-dev \
-    libgtest-dev libgmock-dev \
-    libtool autoconf automake ccache clang-format cppcheck valgrind \
-    gdb htop tmux vim nano tree sudo locales \
+    libavcodec-dev \
+    libavformat-dev \
+    libswscale-dev \
+    libavresample-dev \
+    libv4l-dev \
+    libxvidcore-dev \
+    libx264-dev \
+    libx265-dev \
+    libvpx-dev \
+    && rm -rf /var/lib/apt/lists/*
+
+RUN apt-get update && apt-get install -y \
+    libgstreamer1.0-dev \
+    libgstreamer-plugins-base1.0-dev \
+    libgstreamer-plugins-good1.0-dev \
+    libgstreamer-plugins-bad1.0-dev \
+    gstreamer1.0-plugins-ugly \
+    gstreamer1.0-libav \
+    gstreamer1.0-tools \
+    gstreamer1.0-plugins-good \
+    gstreamer1.0-plugins-bad \
+    && rm -rf /var/lib/apt/lists/*
+
+RUN apt-get update && apt-get install -y \
+    libgtk-3-dev \
+    libgtk2.0-dev \
+    libatlas-base-dev \
+    gfortran \
+    libeigen3-dev \
+    libtbb-dev \
+    libtbb2 \
+    libdc1394-22-dev \
+    && rm -rf /var/lib/apt/lists/*
+
+RUN apt-get update && apt-get install -y \
+    libgl1-mesa-dev \
+    libglu1-mesa-dev \
+    libglew-dev \
+    libxrender-dev \
+    libxrandr-dev \
+    libxcursor-dev \
+    libxinerama-dev \
+    libxi-dev \
+    libxext6 \
+    libsm6 \
+    libice6 \
+    x11-apps \
+    mesa-utils \
+    && rm -rf /var/lib/apt/lists/*
+
+RUN apt-get update && apt-get install -y \
+    ffmpeg \
+    v4l-utils \
+    net-tools \
+    iputils-ping \
+    && rm -rf /var/lib/apt/lists/*
+
+# Librerías C++
+RUN apt-get update && apt-get install -y \
+    libspdlog-dev \
+    libgoogle-glog-dev \
+    libgflags-dev \
+    libfmt-dev \
+    libjsoncpp-dev \
+    nlohmann-json3-dev \
+    libyaml-cpp-dev \
+    libprotobuf-dev \
+    protobuf-compiler \
+    && rm -rf /var/lib/apt/lists/*
+
+RUN apt-get update && apt-get install -y \
+    libmsgpack-dev \
+    libsqlite3-dev \
+    libpq-dev \
+    libmysqlclient-dev \
+    libhiredis-dev \
+    libzmq3-dev \
+    libcurl4-openssl-dev \
+    libssl-dev \
+    libwebsocketpp-dev \
+    libmicrohttpd-dev \
+    && rm -rf /var/lib/apt/lists/*
+
+RUN apt-get update && apt-get install -y \
+    libboost-all-dev \
+    libarmadillo-dev \
+    libopenblas-dev \
+    liblapack-dev \
+    libgsl-dev \
+    libgtest-dev \
+    libgmock-dev \
+    && rm -rf /var/lib/apt/lists/*
+
+RUN apt-get update && apt-get install -y \
+    libtool \
+    autoconf \
+    automake \
+    ccache \
+    clang-format \
+    cppcheck \
+    valgrind \
+    gdb \
+    htop \
+    tmux \
+    vim \
+    nano \
+    tree \
+    sudo \
+    locales \
     && rm -rf /var/lib/apt/lists/*
 
 # Compilar Google Test
-RUN cd /usr/src/gtest && \
-    cmake . && make && \
-    cp lib/*.a /usr/lib || cp *.a /usr/lib || true
+RUN cd /usr/src/gtest && cmake . && make && cp lib/*.a /usr/lib || cp *.a /usr/lib || true
 
-# ===== HEADERS-ONLY LIBRARIES =====
+# Headers-only libraries
 WORKDIR /tmp
 
 RUN git clone --depth 1 https://github.com/CLIUtils/CLI11.git && \
@@ -113,69 +211,74 @@ RUN git clone --depth 1 --branch v3.3.0 https://github.com/catchorg/Catch2.git &
     cmake .. && make install && \
     cd /tmp && rm -rf Catch2
 
-# ===== PYTHON Y NUMPY =====
+# Python y NumPy
 RUN apt-get update && apt-get install -y \
-    python3-pip python3-dev python3-numpy \
+    python3-pip \
+    python3-dev \
+    python3-numpy \
     && rm -rf /var/lib/apt/lists/*
 
 RUN python3 -m pip install --no-cache-dir --upgrade pip
 
-RUN pip3 install --no-cache-dir \
-    packaging setuptools wheel "numpy<2.0" Cython
+RUN pip3 install --no-cache-dir packaging setuptools wheel "numpy<2.0" Cython
 
-# ===== COMPILAR OPENCV CON GCC 9 Y CUDA =====
+# Compilar OpenCV con GCC 9
 RUN update-alternatives --set gcc /usr/bin/gcc-9
+
 ENV CC=/usr/bin/gcc-9
 ENV CXX=/usr/bin/g++-9
 
 WORKDIR /tmp
-RUN git clone --depth 1 --branch ${OPENCV_VERSION} https://github.com/opencv/opencv.git \
-    && git clone --depth 1 --branch ${OPENCV_VERSION} https://github.com/opencv/opencv_contrib.git \
-    && cd opencv && mkdir build && cd build \
-    && cmake \
-        -D CMAKE_BUILD_TYPE=RELEASE \
-        -D CMAKE_INSTALL_PREFIX=/usr/local \
-        -D CMAKE_CXX_STANDARD=17 \
-        -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
-        -D WITH_CUDA=ON \
-        -D CUDA_ARCH_BIN="8.7" \
-        -D CUDA_ARCH_PTX="" \
-        -D ENABLE_FAST_MATH=ON \
-        -D CUDA_FAST_MATH=ON \
-        -D WITH_CUBLAS=ON \
-        -D WITH_CUDNN=ON \
-        -D OPENCV_DNN_CUDA=ON \
-        -D WITH_NVCUVID=ON \
-        -D WITH_LIBV4L=ON \
-        -D WITH_V4L=ON \
-        -D WITH_GSTREAMER=ON \
-        -D WITH_FFMPEG=ON \
-        -D WITH_GTK=ON \
-        -D WITH_QT=OFF \
-        -D WITH_OPENGL=ON \
-        -D WITH_TBB=OFF \
-        -D WITH_EIGEN=ON \
-        -D WITH_LAPACK=ON \
-        -D BUILD_opencv_python3=ON \
-        -D BUILD_TESTS=OFF \
-        -D BUILD_PERF_TESTS=OFF \
-        -D BUILD_EXAMPLES=OFF \
-        -D OPENCV_ENABLE_NONFREE=ON \
-        -D OPENCV_GENERATE_PKGCONFIG=ON \
-        -D BUILD_opencv_cudacodec=ON \
-        -D CMAKE_CXX_FLAGS="-O3" \
-        .. \
-    && make -j$(nproc) \
-    && make install \
-    && ldconfig \
-    && cd / && rm -rf /tmp/opencv /tmp/opencv_contrib
+RUN git clone --depth 1 --branch ${OPENCV_VERSION} https://github.com/opencv/opencv.git
+RUN git clone --depth 1 --branch ${OPENCV_VERSION} https://github.com/opencv/opencv_contrib.git
 
-# ===== VOLVER A GCC 11 =====
+RUN cd opencv && mkdir build && cd build && \
+    cmake \
+    -D CMAKE_BUILD_TYPE=RELEASE \
+    -D CMAKE_INSTALL_PREFIX=/usr/local \
+    -D CMAKE_CXX_STANDARD=17 \
+    -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
+    -D WITH_CUDA=ON \
+    -D CUDA_ARCH_BIN="8.7" \
+    -D CUDA_ARCH_PTX="" \
+    -D ENABLE_FAST_MATH=ON \
+    -D CUDA_FAST_MATH=ON \
+    -D WITH_CUBLAS=ON \
+    -D WITH_CUDNN=ON \
+    -D OPENCV_DNN_CUDA=ON \
+    -D WITH_NVCUVID=ON \
+    -D WITH_LIBV4L=ON \
+    -D WITH_V4L=ON \
+    -D WITH_GSTREAMER=ON \
+    -D WITH_FFMPEG=ON \
+    -D WITH_GTK=ON \
+    -D WITH_QT=OFF \
+    -D WITH_OPENGL=ON \
+    -D WITH_TBB=OFF \
+    -D WITH_EIGEN=ON \
+    -D WITH_LAPACK=ON \
+    -D BUILD_opencv_python3=ON \
+    -D BUILD_TESTS=OFF \
+    -D BUILD_PERF_TESTS=OFF \
+    -D BUILD_EXAMPLES=OFF \
+    -D OPENCV_ENABLE_NONFREE=ON \
+    -D OPENCV_GENERATE_PKGCONFIG=ON \
+    -D BUILD_opencv_cudacodec=ON \
+    -D CMAKE_CXX_FLAGS="-O3" \
+    ..
+
+RUN cd opencv/build && make -j$(nproc)
+RUN cd opencv/build && make install
+RUN ldconfig
+RUN rm -rf /tmp/opencv /tmp/opencv_contrib
+
+# Volver a GCC 11
 RUN update-alternatives --set gcc /usr/bin/gcc-11
+
 ENV CC=/usr/bin/gcc-11
 ENV CXX=/usr/bin/g++-11
 
-# ===== PAQUETES PYTHON Y JUPYTERLAB =====
+# Paquetes Python
 RUN pip3 install --no-cache-dir \
     notebook \
     jupyterlab \
@@ -189,7 +292,7 @@ RUN pip3 install --no-cache-dir \
     tqdm \
     opencv-python-headless
 
-# ===== TEMAS JUPYTERLAB =====
+# Temas JupyterLab
 RUN pip3 install --no-cache-dir \
     jupyterlab-catppuccin \
     jupyterlab-hale-theme \
@@ -198,24 +301,20 @@ RUN pip3 install --no-cache-dir \
 
 RUN jupyter labextension list || true
 
-# ===== CONFIGURACIÓN JUPYTERLAB =====
-RUN mkdir -p ~/.jupyter/lab/user-settings/@jupyterlab/apputils-extension && \
-    echo '{ \
-      "theme": "Catppuccin Mocha", \
-      "theme-scrollbars": true, \
-      "overrides": { \
-        "preferredDarkTheme": "Catppuccin Mocha", \
-        "preferredLightTheme": "Hale" \
-      } \
-    }' > ~/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/themes.jupyterlab-settings
+# Configuración JupyterLab
+RUN mkdir -p ~/.jupyter/lab/user-settings/@jupyterlab/apputils-extension
 
-RUN mkdir -p ~/.jupyter/lab/user-settings/@jupyterlab/translation-extension && \
-    echo '{ \
-      "locale": "es-ES" \
-    }' > ~/.jupyter/lab/user-settings/@jupyterlab/translation-extension/plugin.jupyterlab-settings
+RUN echo '{"theme":"Catppuccin Mocha","theme-scrollbars":true,"overrides":{"preferredDarkTheme":"Catppuccin Mocha","preferredLightTheme":"Hale"}}' > \
+    ~/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/themes.jupyterlab-settings
 
-RUN mkdir -p ~/.jupyter && \
-    echo "c.ServerApp.ip = '0.0.0.0'" > ~/.jupyter/jupyter_server_config.py && \
+RUN mkdir -p ~/.jupyter/lab/user-settings/@jupyterlab/translation-extension
+
+RUN echo '{"locale":"es-ES"}' > \
+    ~/.jupyter/lab/user-settings/@jupyterlab/translation-extension/plugin.jupyterlab-settings
+
+RUN mkdir -p ~/.jupyter
+
+RUN echo "c.ServerApp.ip = '0.0.0.0'" > ~/.jupyter/jupyter_server_config.py && \
     echo "c.ServerApp.port = 8888" >> ~/.jupyter/jupyter_server_config.py && \
     echo "c.ServerApp.allow_root = True" >> ~/.jupyter/jupyter_server_config.py && \
     echo "c.ServerApp.open_browser = False" >> ~/.jupyter/jupyter_server_config.py && \
@@ -224,45 +323,45 @@ RUN mkdir -p ~/.jupyter && \
 
 EXPOSE 8888
 
-# ===== LDCONFIG =====
-RUN echo "/usr/local/cuda/lib64" > /etc/ld.so.conf.d/cuda.conf \
-    && echo "/usr/lib/aarch64-linux-gnu/tegra" > /etc/ld.so.conf.d/tegra.conf \
-    && echo "/usr/lib/aarch64-linux-gnu/tegra-egl" >> /etc/ld.so.conf.d/tegra.conf \
-    && echo "/usr/local/lib" > /etc/ld.so.conf.d/local.conf \
-    && ldconfig
+# ldconfig
+RUN echo "/usr/local/cuda/lib64" > /etc/ld.so.conf.d/cuda.conf
+RUN echo "/usr/lib/aarch64-linux-gnu/tegra" > /etc/ld.so.conf.d/tegra.conf
+RUN echo "/usr/lib/aarch64-linux-gnu/tegra-egl" >> /etc/ld.so.conf.d/tegra.conf
+RUN echo "/usr/local/lib" > /etc/ld.so.conf.d/local.conf
+RUN ldconfig
 
-# ===== LOCALE Y TIMEZONE =====
-RUN locale-gen es_ES.UTF-5 en_US.UTF-5 \
-    && update-locale LANG=es_ES.UTF-5 LANGUAGE=es_ES:es LC_ALL=es_ES.UTF-5
+# Locale y timezone
+RUN locale-gen es_ES.UTF-8 en_US.UTF-8
+RUN update-locale LANG=es_ES.UTF-8 LANGUAGE=es_ES:es LC_ALL=es_ES.UTF-8
 
-# ===== GIT CONFIG =====
-RUN git config --global user.email "gerald.cainicela.a@gmail.com" \
-    && git config --global user.name "userasd" \
-    && git config --global --add safe.directory '*'
+# Git config
+RUN git config --global user.email "gerald.cainicela.a@gmail.com"
+RUN git config --global user.name "userasd"
+RUN git config --global --add safe.directory '*'
 
-RUN ln -sf /usr/share/zoneinfo/America/Lima /etc/localtime && \
-    echo "America/Lima" > /etc/timezone
+RUN ln -sf /usr/share/zoneinfo/America/Lima /etc/localtime
+RUN echo "America/Lima" > /etc/timezone
 
-# ===== DIRECTORIOS =====
+# Directorios
 RUN mkdir -p /workspace /var/log /opt/tests
 
-# ===== COPIAR ARCHIVOS =====
+# Copiar archivos
 COPY docker-entrypoint.sh /usr/local/bin/
 RUN chmod +x /usr/local/bin/docker-entrypoint.sh
 
 COPY test/ /opt/tests/
 RUN chmod +x /opt/tests/*.sh /opt/tests/*.py 2>/dev/null || true
 
-# ===== CREAR SCRIPT DE VERIFICACIÓN RÁPIDA =====
-RUN echo '#!/bin/bash\n\
-echo "=== Quick Verification ==="\n\
-echo "GCC: $(gcc --version | head -n1)"\n\
-echo "CMake: $(cmake --version | head -n1)"\n\
-echo "OpenCV: $(pkg-config --modversion opencv4 2>/dev/null || echo \"Not found\")"\n\
-echo "CUDA Devices: $(python3 -c \"import cv2; print(cv2.cuda.getCudaEnabledDeviceCount())\" 2>/dev/null || echo \"0\")"\n\
-echo "TensorRT: $(ls /usr/lib/aarch64-linux-gnu/libnvinfer.so* 2>/dev/null | head -n1 || echo \"Not found\")"\n\
-echo "JupyterLab: http://localhost:8888 (token: nvidia)"\n\
-' > /usr/local/bin/quick-check && chmod +x /usr/local/bin/quick-check
+# Script de verificación rápida
+RUN echo '#!/bin/bash' > /usr/local/bin/quick-check && \
+    echo 'echo "=== Quick Verification ==="' >> /usr/local/bin/quick-check && \
+    echo 'echo "GCC: $(gcc --version | head -n1)"' >> /usr/local/bin/quick-check && \
+    echo 'echo "CMake: $(cmake --version | head -n1)"' >> /usr/local/bin/quick-check && \
+    echo 'echo "OpenCV: $(pkg-config --modversion opencv4 2>/dev/null || echo Not found)"' >> /usr/local/bin/quick-check && \
+    echo 'echo "CUDA Devices: $(python3 -c \"import cv2; print(cv2.cuda.getCudaEnabledDeviceCount())\" 2>/dev/null || echo 0)"' >> /usr/local/bin/quick-check && \
+    echo 'echo "TensorRT: $(ls /usr/lib/aarch64-linux-gnu/libnvinfer.so* 2>/dev/null | head -n1 || echo Not found)"' >> /usr/local/bin/quick-check && \
+    echo 'echo "JupyterLab: http://localhost:8888 (token: nvidia)"' >> /usr/local/bin/quick-check && \
+    chmod +x /usr/local/bin/quick-check
 
 WORKDIR /workspace
 
